SUBROUTINE TOTO(KLON, POUT1, POUT2, ILEVOUT)

IMPLICIT NONE
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
REAL(KIND=JPRD) :: ZOUTS(KPROMA)
REAL (KIND=JPRB), OPTIONAL, INTENT (OUT)::POUT1 (KPROMA,*)
!REAL (KIND=JPRB), OPTIONAL, INTENT (OUT)::POUT2 (KPROMA,KFLEV)

!POUT1(:,ILEVOUT) = ZOUTS(:)
!POUT2(:,ILEVOUT) = ZOUTS(:)


END SUBROUTINE TOTO
