SUBROUTINE TOTO(A,B)

IMPLICIT NONE
REAL, INTENT(IN) :: A
REAL, INTENT(INOUT) :: B


!$ACC PARALLEL LOOP GANG &
!$ACC&PRESENT (YDCPG_OPTS, YDMODEL, YSTACK, ZFLX_LOTT_GWU, ZFLX_LOTT_GWV, ZFPCOR, ZFPLSL, ZFPLSN, ZPFL_FPLCH, ZPFL_FPLSH, ZQI, ZQL, ZQV, ZSEDIQI, ZSEDIQL, Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_XYB_RDELP, Z_YDMF_PHYS_OUT_DIFCQ, Z_YDMF_PHYS_OUT_DIFCQL, Z_YDMF_PHYS_OUT_DIFCQN, Z_YDMF_PHYS_OUT_DIFTQ, Z_YDMF_PHYS_OUT_DIFTQL, Z_YDMF_PHYS_OUT_DIFTQN, Z_YDMF_PHYS_OUT_FCCQL, Z_YDMF_PHYS_OUT_FCCQN, Z_YDMF_PHYS_OUT_FCQNG, Z_YDMF_PHYS_OUT_FCSQL, Z_YDMF_PHYS_OUT_FCSQN, Z_YDMF_PHYS_OUT_FPEVPCL, Z_YDMF_PHYS_OUT_FPEVPCN, Z_YDMF_PHYS_OUT_FPEVPSL, Z_YDMF_PHYS_OUT_FPEVPSN, Z_YDMF_PHYS_OUT_FPFPCL, Z_YDMF_PHYS_OUT_FPFPCN, Z_YDMF_PHYS_OUT_FPFPSL, Z_YDMF_PHYS_OUT_FPFPSN, Z_YDMF_PHYS_OUT_FPLSG, Z_YDMF_PHYS_OUT_FPLSL, Z_YDMF_PHYS_OUT_FPLSN) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON)


END SUBROUTINE TOTO
