SUBROUTINE TOTO(A,B)

IMPLICIT NONE
REAL, INTENT(IN) :: A
REAL, INTENT(INOUT) :: B


!$ACC PARALLEL LOOP GANG &
!$ACC&PRESENT(ZRDG_LCVQ,ZFLU_QSATS,ZRDG_CVGQ) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON)


END SUBROUTINE TOTO
