SUBROUTINE DISPATCH_ROUTINE(YDCPG_OPTS)

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE

IMPLICIT NONE

TYPE(CPG_OPTS_TYPE),            INTENT(IN)    :: YDCPG_OPTS

REAL(KIND=JPRB)     :: ZRDG_MU0 (YDCPG_OPTS%KLON)


END SUBROUTINE DISPATCH_ROUTINE
