SUBROUTINE TEST(KLON,PT)

USE PARKIND1  ,ONLY : JPIM, JPRB

IMPLICIT NONE

INTEGER(KIND=JPIM) ,INTENT(IN)   :: KLON
REAL(KIND=JPRB)    ,INTENT(IN)   :: PT(KLON)
INTEGER(KIND=JPIM) :: JLON

DO JLON=1,10
PRINT *,'HI'
PT(JLON) = 1.0
ENDDO

END SUBROUTINE TEST
